<a href="https://colab.research.google.com/github/aryansuri42/IAIML-Sem5/blob/main/IAIML_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
from sklearn.impute import SimpleImputer
import pandas as pd
df = pd.read_csv("/content/Data.csv")
df1 = df.copy()
df2 = df.copy()
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [36]:
len(df)

10

In [37]:
col_list = list(df.columns)

In [38]:
null_cols = []
for i in col_list:
  if df[i].isnull().values.any() == True:
    null_cols.append(i)
null_cols

['Age', 'Salary']

In [39]:
imp = SimpleImputer(strategy="mean")
for col in null_cols:
  df[col] = imp.fit_transform(df[col].values.reshape(-1,1))
df

   Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [40]:
imp = SimpleImputer(strategy="most_frequent")
for col in null_cols:
  df1[col] = imp.fit_transform(df1[col].values.reshape(-1,1))
df1

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  48000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  27.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [41]:
imp = SimpleImputer(strategy="median")
for col in null_cols:
  df2[col] = imp.fit_transform(df2[col].values.reshape(-1,1))
df2

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes